### PR TITLE
Animating sim (slightly broken)

### PR DESCRIPTION
**Pull request by henryiii**
@davidlange6 I've added a basic animation, but it's broken - can you fix it? I've also cleaned up some parts to make it easier for me to work on - you can checkout from an older version and go from there if you really prefer.

### CODE REVIEW

**Comment by davidlange6** [comment]
@henryiii @pelmer - I think rather than animating the simulation we should agree on the data input to the GUI and then show the simulation results animated via that - eg, develop the simulation to feed data in "real time" (or sped up real time) to the GUI. 

But to do that we need to specify the data format that the GUI expects from the patient stations.

**Comment by pelmer** [comment]
I agree. Next step has to be the data format which we can feed both from the simulation and from the sensors for data transfer to the nurse station

**Comment by henryiii** [comment]
We have a data format (that needs to be changed/refined), and the sim can talk to the GUI already. I need something that changes do I know it doesn't die. I also want to drop this into the GUI itself so I can have three lines instead of one.

**Comment by davidlange6** [comment]
ok- I see what you have for a data format - sorry I missed this earlier. I'd suggest that we have the sim make data packets. I suck at reading xml parsing code - a packet is

<ventsensor>
<data>
<time> What format do you want time to be in </time>
<flow> 10.0 </flow>
</data>
</ventsensor>

then some next tags:
 1) how do we batch up the 1 second of data? A series of data tags? 
 2) how do we label sensors - should I use 1..20 for now and include that as part of the data field?

is that right? (modulo my question) I can make the simulation

**Comment by davidlange6** [comment]
on the code animation - I suspect the issue is in the get_breath_starts - but I didn't follow what "current_time" is meant to do - I first thought the idea was to extend the x axis of the plots with more "time" points. Is that correct?

**Comment by henryiii** [comment]
Time can either be computed from 0 (the current format has time as -N to 0, and records a separate "absolute" time, which tells you what 0 actually is, or it could be an absolute number. The current data format is in the first form. If that's the case, then "t" doesn't even need to be sent - you can simply push the single absolute time.

I'm going to move from xml to json soon, it should be easier to read the parsing/generation code and it should be faster and less data, too.

**Comment by henryiii** [comment]
I was trying to have "current_time" simply slide the waveform, but maybe not affect the reporting of "t" at all (I was mixing ideas a bit in the code you see now).

**Comment by davidlange6** [comment]
ok - I taught send about to take the last time stamp and feed it back into the next simulation run.
so the x-axis now moves.
next thing is to keep track of the last breath time so that the series of breaths moves too. I'll do that now.

I committed it directly - so closing this.

**Comment by henryiii** [comment]
I'm still getting, every so often:

```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1187, in _on_timer
    ret = func(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/animation.py", line 1449, in _step
    still_going = Animation._step(self, *args)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/animation.py", line 1169, in _step
    self._draw_next_frame(framedata, self._blit)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/animation.py", line 1189, in _draw_next_frame
    self._post_draw(framedata, blit)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/animation.py", line 1212, in _post_draw
    self._blit_draw(self._drawn_artists, self._blit_cache)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/animation.py", line 1233, in _blit_draw
    a.axes.draw_artist(a)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2644, in draw_artist
    a.draw(self.figure._cachedRenderer)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/lines.py", line 759, in draw
    self.recache()
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/lines.py", line 679, in recache
    self._xy = np.column_stack(np.broadcast_arrays(x, y)).astype(float)
  File "<__array_function__ internals>", line 6, in broadcast_arrays
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 264, in broadcast_arrays
    shape = _broadcast_shape(*args)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 191, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

**Comment by davidlange6** [comment]
Maybe I just hit a related bug (but I’m not using the matplotlib functionality)

On Apr 7, 2020, at 6:55 PM, Henry Schreiner <notifications@github.com<mailto:notifications@github.com>> wrote:



I'm still getting, every so often:

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1187, in _on_timer
    ret = func(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/animation.py", line 1449, in _step
    still_going = Animation._step(self, *args)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/animation.py", line 1169, in _step
    self._draw_next_frame(framedata, self._blit)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/animation.py", line 1189, in _draw_next_frame
    self._post_draw(framedata, blit)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/animation.py", line 1212, in _post_draw
    self._blit_draw(self._drawn_artists, self._blit_cache)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/animation.py", line 1233, in _blit_draw
    a.axes.draw_artist(a)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2644, in draw_artist
    a.draw(self.figure._cachedRenderer)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/lines.py", line 759, in draw
    self.recache()
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/matplotlib/lines.py", line 679, in recache
    self._xy = np.column_stack(np.broadcast_arrays(x, y)).astype(float)
  File "<__array_function__ internals>", line 6, in broadcast_arrays
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 264, in broadcast_arrays
    shape = _broadcast_shape(*args)
  File "/usr/local/Caskroom/miniconda/base/envs/flowmeter/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 191, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape

**Pull request closed without merging**
