### PR TITLE
Trying for a scrolling view

### PR DESCRIPTION
**Pull request by henryiii**
@davidlange6 I'm trying to make a scrolling time window that reports when it is queried. I don't think it looks quite right - it's not moving smoothly at 1 second intervals AFAICT.

### CODE REVIEW

**Comment by henryiii** [comment]
By the way, we might report a shorter time frame if this is too much to send (say, 10 seconds), but I want the contents of the packet to depend only on the time, not the number or order of requests. It should be valid to monitor this from two places. If we just "empty" every time we view it, we can't view it locally and at the nurse station, for example (and it's much harder to debug and more error prone).

**Comment by davidlange6** [comment]
hi @henryiii - Right, somebody has to keep a buffer of data. But its not the simulation in the end - which should provide data like it will come from the detectors (which won't buffer the data).

did we decide who that was? Patient side or nurse side or both? We don't have a start on the patient side consumption of data as far as I see. Making the patient side the only holder of a buffer means 20* 50Hz*1 minute * 3 quantities + N alarm / analysis states each time the nurse station is updated.  If we had binary data, thats 10MB/second. Let me check what json formatting does to that.

@pelmer @jpivarski

**Comment by davidlange6** [comment]
if aggregate.py does the right thing - then 1 minute of data at 50 Hz from one patient is O(200kB) of json (but without volumes included). so thats not a problem to do 20 times a second.

**Comment by davidlange6** [comment]
I will work on something for the patient side in 1-2 hours.

**Comment by henryiii** [comment]
I'd like to simulate this in simulation because I'm using it to work out the details of how much free processing power I have at the nursing station. I don't know if we can run 20 copies of the patient software until we have 20 devices to run it on; that's why the batching simulation is useful. At 5 minutes, I'm reading too much. The format I think would be best is that at any time a request is made, the patient box can deliver 5 seconds of past data. The nursing station ideally could also make a special request for the entire rolling buffer the first time it connects. Then, if it makes a request once per second, there's still a nice safety margin.

The patient side *must* keep a longer buffer (5 minutes?) so that it can calculate breathing rate and various alarms.

I've developed a rolling buffer we can probably use for simulation, and definitely use for the nurse and the patient software. I'm going to work on integrating it into nurse and start the patient loop. Let me know where you are so we don't end up writing the same thing. :)

**Pull request closed without merging**
