### PR TITLE
MAC addresses to words

### PR DESCRIPTION
**Pull request by jpivarski**

### CODE REVIEW

**Comment by henryiii** [comment]
Some of the words are longer than 6 chars; was the idea to have 6 each?

**Comment by henryiii** [comment]
Note, if we really have to, we could split up the display and have one on the top, two on the bottom; but that would leave us little room to explain what we are saying. `Box name:` would fit, though.

**Comment by jpivarski** [comment]
With this definition, our first batch of devices are named:

```
dc:a6:32:8f:67:58 -> cloudy pat
dc:a6:32:8f:67:46 -> time tooth
dc:a6:32:82:f6:a2 -> valuable canyon
dc:a6:32:83:73:79 -> experimental chunk
dc:a6:32:8f:55:64 -> regal tactile
dc:a6:32:83:73:4f -> eastern wardrobe
dc:a6:32:8f:67:8b -> untenable text
dc:a6:32:87:49:e7 -> unfamiliar outset
dc:a6:32:8f:67:0e -> abundant creek
dc:a6:32:83:73:b5 -> ceaseless doubter
dc:a6:32:83:71:84 -> dressy clavicle
dc:a6:32:80:73:99 -> glum seeder
dc:a6:32:83:6f:fb -> warlike bull
dc:a6:32:87:4a:11 -> timorous puzzle
dc:a6:32:83:73:3d -> such feather
dc:a6:32:87:4c:a2 -> liable ability
dc:a6:32:84:e4:2e -> conformable lily
dc:a6:32:83:71:45 -> cohesive macro
dc:a6:32:71:76:71 -> international clock
dc:a6:32:82:99:ba -> unhurried camp
```

**Edit:** with the old parameters, the pseudorandom updater was only populating 5% of the set of words. Now the parameters have a modulus of `2**24` and exactly cover the set of words. (The other two parameters were chosen from a [table on Wikipedia](https://en.wikipedia.org/wiki/Linear_congruential_generator#Parameters_in_common_use) that shows parameter sets in common use. This new set, with a `2**24` modulus, was used by Visual Basic up to version 6, so it must have been okayish.

**Comment by jpivarski** [comment]
With this set of 4096 adjectives and 4096 nouns, the longest adjectives are 12 characters long, the longest nouns are 8 characters long, and in the 0.96% chance that you get the longest of each (20 characters, which would be 21 characters with the space), it tries another combination in a strictly reproducible way:

https://github.com/Princeton-Penn-Vents/princeton-penn-flowmeter/blob/d976fc699f56df2b0ff0ad9265739a3412b9e8ef/mac_to_words.py#L37-L42

The same is true if it ever encounters a blank adjective or a blank noun. None of the adjectives or nouns are currently blank. The idea is that if we ever produce a word that we we've never encountered before and it's objectionable, we can blank it out of the list. That doesn't affect any previous identifiers (because we've never complained before) and we don't have to update old software, but the new combination would try again.

**Comment by jpivarski** [comment]
To keep things transparent, we're just mapping the lower bits of `state` to words in the randomly ordered lists of adjectives and nouns. The `state` is derived from the non-vendor bits of the MAC address and is at least one step in the pseudorandom sequence defined by

https://github.com/Princeton-Penn-Vents/princeton-penn-flowmeter/blob/d976fc699f56df2b0ff0ad9265739a3412b9e8ef/mac_to_words.py#L8-L10

This LCG generator has a [rather low cycle](https://indico.cern.ch/event/814979/contributions/3401176/attachments/1831472/3107702/RandomAbuse2019.pdf), like a million or something, but we're taking an extremely small number of steps in the sequence: usually 1, but 2 or 3 if we hit some exception, such as using a second vendor:

https://github.com/Princeton-Penn-Vents/princeton-penn-flowmeter/blob/d976fc699f56df2b0ff0ad9265739a3412b9e8ef/mac_to_words.py#L1

https://github.com/Princeton-Penn-Vents/princeton-penn-flowmeter/blob/d976fc699f56df2b0ff0ad9265739a3412b9e8ef/mac_to_words.py#L27-L35

or hitting a 21 character combination or a removed word or something. By defining our own random sequencer, we're not dependent on any changes in Python's built-in algorithm.

As we move forward, the rules for our schema evolution are:

   1. If we ever start using a new ethernet card vendor (as defined by the 24 high bits), we have to append that vendor at the _end_ of the list.
   2. We can blank out words that we've never hit before, but we can't remove the lines from the file. It _has to_ become an empty line, leaving all other lines where they are.

Old software that has been deployed does not need to be updated to yield exactly the same results as software updated according to these rules.

Even though we start with MAC addresses that are guaranteed unique, the result of this algorithm is not guaranteed unique. However, the chance of collision is 1 in 16 million. That's good enough for display names that are backed up by truly unique ethernet addresses.

**Comment by jpivarski** [comment]
@henryiii Once we sign off on this, I can move the function to a place where it belongs.

Are we ever pip-installing the package? Do I need to get adjectives.txt and nouns.txt into `data_files` or something?

**Comment by henryiii** [comment]
We may switch to that model. I was always rather intending to (you'll see some comments in the code about it), but dropped the idea due to the short timespan. Now we might really want the data and code to be separate (since cutting the power corrupts nearby bits in the flash drive), so it might get bumped up in priority.

I'll check to make sure the package matches SCM, though, so it should be okay to not put this in a datafiles yet.

**Comment by henryiii** [comment]
I thought we were doing 3 words, so we could have a nice 3 char initial? It's not absolutely required, but was a bit nice. I'll design around it if we don't have 3, though.

**Comment by jpivarski** [comment]
> I thought we were doing 3 words, so we could have a nice 3 char initial? It's not absolutely required, but was a bit nice. I'll design around it if we don't have 3, though.

Since the space of addresses that we care about is only 24 bits (16 million possibilities), rather than 48 bits (300 trillion), we can get away with only 2 words. That's better for human-friendliness, because now it's plausible that someone could even remember it verbatim or be able to disambiguate a handful without having to check. Apart from alliteration, they're now about as recognizable as Ubuntu release names.

A 2 character initial would fit in the corner even better, right? I think you currently have two characters reserved for a 2 digit number, so this could fit there without having to move anything else to adjust.

If you want to use a third character and the patient boxes can see all the MAC addresses on the network as easily as the nurse GUI can, they could, potentially, represent themselves as two letters and a space if unambiguous or two letters and a number otherwise. The number could be assigned by lexicographically comparing the conflicting names. Every box is equally capable of translating MAC addresses into the same names: there wouldn't be any race conditions for deciding which should get the smaller number—it's a pure function of the immutable MAC addresses. If this complicates things, though, we should just forget about this suggestion. This would only be if it's really easy for each box to get a list of all MAC addresses on the network—I could write the abbreviation-and-number function rather easily.

**Pull request merged**
